INSERT INTO vendor (VendorID, VendorName, ContactInfo) 
VALUES 
(4, "Coke", "contact@coke.com"),
(5, "Pepsi", "contact@pepsi.com"),
(6, "Nestle", "contact@nestle.com"),
(7, "Unilever", "contact@unilever.com"),
(8, "Procter & Gamble", "contact@pg.com"),
(9, "Kraft Heinz", "contact@kraftheinz.com"),
(10, "General Mills", "contact@generalmills.com"),
(11, "Danone", "contact@danone.com"),
(12, "Ferrero", "contact@ferrero.com"),
(13, "Kellogg's", "contact@kelloggs.com"),
(14, "Mars", "contact@mars.com"),
(15, "Mondelez", "contact@mondelez.com"),
(16, "Tyson Foods", "contact@tysonfoods.com"),
(17, "Cargill", "contact@cargill.com"),
(18, "Archer Daniels Midland", "contact@adm.com"),
(19, "Hormel Foods", "contact@hormel.com"),
(20, "Conagra Brands", "contact@conagra.com"),
(21, "JBS", "contact@jbs.com"),
(22, "Smithfield Foods", "contact@smithfield.com"),
(23, "Sysco", "contact@sysco.com"),
(24, "McCain Foods", "contact@mccain.com"),
(25, "Bimbo Bakeries", "contact@bimbobakeries.com"),
(26, "Flowers Foods", "contact@flowersfoods.com"),
(27, "Grupo Lala", "contact@grupolala.com"),
(28, "Saputo", "contact@saputo.com"),
(29, "Dean Foods", "contact@deanfoods.com"),
(30, "Meiji Holdings", "contact@meiji.com"),
(31, "Ajinomoto", "contact@ajinomoto.com"),
(32, "Yili Group", "contact@yili.com"),
(33, "Mengniu Dairy", "contact@mengniu.com"),
(34, "FrieslandCampina", "contact@frieslandcampina.com"),
(35, "Arla Foods", "contact@arla.com"),
(36, "Fonterra", "contact@fonterra.com"),
(37, "Saputo", "contact@saputo.com"),
(38, "Barry Callebaut", "contact@barry-callebaut.com"),
(39, "Godiva", "contact@godiva.com"),
(40, "Hershey", "contact@hersheys.com"),
(41, "Lindt & Sprüngli", "contact@lindt.com"),
(42, "Guylian", "contact@guylian.com"),
(43, "Ghirardelli", "contact@ghirardelli.com"),
(44, "Toblerone", "contact@toblerone.com"),
(45, "Cadbury", "contact@cadbury.com"),
(46, "Chupa Chups", "contact@chupachups.com"),
(47, "Haribo", "contact@haribo.com"),
(48, "Wrigley", "contact@wrigley.com"),
(49, "Skittles", "contact@skittles.com"),
(50, "Nestle Water", "contact@nestlewater.com");
