INSERT INTO store (StoreID, StoreName, Location, HoursOfOperation) 
VALUES 
(6, "MetroMart Shinjuku", "2-chome Shinjuku-dori, Tokyo, Japan", "24/7"),
(7, "FreshMart New York", "5th Avenue, New York, USA", "7 AM - 10 PM"),
(8, "Seoul Grocery", "Gangnam-gu, Seoul, Korea", "8 AM - 11 PM"),
(9, "London Grocers", "Oxford Street, London, UK", "6 AM - 10 PM"),
(10, "Paris Market", "Champs-Élysées, Paris, France", "8 AM - 9 PM"),
(11, "Sydney Supermarket", "George Street, Sydney, Australia", "7 AM - 9 PM"),
(12, "Beijing Bazaar", "Chaoyang District, Beijing, China", "9 AM - 9 PM"),
(13, "Toronto Market", "Yonge Street, Toronto, Canada", "8 AM - 10 PM"),
(14, "Osaka OpenMart", "Namba District, Osaka, Japan", "24/7"),
(15, "Chicago FreshMart", "Magnificent Mile, Chicago, USA", "6 AM - 10 PM"),
(16, "Busan Market", "Haeundae District, Busan, Korea", "8 AM - 10 PM"),
(17, "Manchester Groceries", "Deansgate, Manchester, UK", "7 AM - 10 PM"),
(18, "Lyon Foods", "Rue de la République, Lyon, France", "8 AM - 8 PM"),
(19, "Melbourne Mart", "Swanston Street, Melbourne, Australia", "6 AM - 9 PM"),
(20, "Shanghai Market", "Pudong District, Shanghai, China", "9 AM - 9 PM"),
(21, "Vancouver Market", "Granville Street, Vancouver, Canada", "7 AM - 9 PM"),
(22, "Nagoya Grocers", "Sakae District, Nagoya, Japan", "24/7"),
(23, "Los Angeles SuperMart", "Santa Monica Boulevard, Los Angeles, USA", "6 AM - 10 PM"),
(24, "Daegu FreshMart", "Dongseong-ro, Daegu, Korea", "8 AM - 9 PM"),
(25, "Birmingham Foods", "Bullring, Birmingham, UK", "7 AM - 10 PM"),
(26, "Marseille Market", "La Canebière, Marseille, France", "9 AM - 8 PM"),
(27, "Perth Groceries", "Hay Street, Perth, Australia", "7 AM - 9 PM"),
(28, "Guangzhou Foods", "Tianhe District, Guangzhou, China", "9 AM - 9 PM"),
(29, "Montreal Mart", "Rue Sainte-Catherine, Montreal, Canada", "8 AM - 10 PM"),
(30, "Kyoto Grocery", "Gion District, Kyoto, Japan", "24/7"),
(31, "Houston Foods", "Main Street, Houston, USA", "6 AM - 11 PM"),
(32, "Incheon Mart", "Songdo District, Incheon, Korea", "7 AM - 9 PM"),
(33, "Leeds Market", "Briggate, Leeds, UK", "8 AM - 10 PM"),
(34, "Toulouse Groceries", "Place du Capitole, Toulouse, France", "9 AM - 8 PM"),
(35, "Adelaide Market", "Rundle Mall, Adelaide, Australia", "6 AM - 8 PM"),
(36, "Hong Kong Bazaar", "Central District, Hong Kong, China", "24/7"),
(37, "Calgary Mart", "Stephen Avenue, Calgary, Canada", "8 AM - 9 PM"),
(38, "Kobe Market", "Motomachi, Kobe, Japan", "24/7"),
(39, "Phoenix SuperMart", "Camelback Road, Phoenix, USA", "7 AM - 10 PM"),
(40, "Gwangju Grocery", "Geumnam-ro, Gwangju, Korea", "9 AM - 8 PM"),
(41, "Glasgow Foods", "Buchanan Street, Glasgow, UK", "7 AM - 9 PM"),
(42, "Nice Groceries", "Promenade des Anglais, Nice, France", "8 AM - 8 PM"),
(43, "Brisbane Market", "Queen Street, Brisbane, Australia", "7 AM - 9 PM"),
(44, "Chengdu Groceries", "Jinjiang District, Chengdu, China", "9 AM - 8 PM"),
(45, "Ottawa Mart", "Rideau Street, Ottawa, Canada", "8 AM - 9 PM"),
(46, "Sapporo Market", "Odori Park, Sapporo, Japan", "24/7"),
(47, "San Francisco FreshMart", "Market Street, San Francisco, USA", "6 AM - 10 PM"),
(48, "Daejeon Grocery", "Dunsan-dong, Daejeon, Korea", "8 AM - 9 PM"),
(49, "Liverpool Foods", "Liverpool ONE, Liverpool, UK", "7 AM - 10 PM"),
(50, "Strasbourg Market", "Grand Île, Strasbourg, France", "9 AM - 8 PM"),
(51, "Gold Coast Market", "Surfers Paradise, Gold Coast, Australia", "7 AM - 9 PM"),
(52, "Shenzhen Bazaar", "Nanshan District, Shenzhen, China", "9 AM - 9 PM"),
(53, "Edmonton Mart", "Whyte Avenue, Edmonton, Canada", "7 AM - 9 PM"),
(54, "Hiroshima Grocery", "Hondori, Hiroshima, Japan", "24/7"),
(55, "Boston Foods", "Boylston Street, Boston, USA", "6 AM - 11 PM");
